### ISSUE TITLE
Grammatical advice

### ISSUE THREAD

**Issue by fuqiuluo** [The-Ray-Language/raylang.design#2]
- Change the package from '@get' to 'use'

```
use console
console.log("1")

use console as con
con.log("2")

use console.{log, info}
log("3")

use console.{...}
log("4")
info("5")
```

**Comment by DiamondHunters** [comment]
> * Change the package from '@get' to 'use'
> 
> ```
> use console
> console.log("1")
> 
> use console as con
> con.log("2")
> 
> use console.{log, info}
> log("3")
> 
> use console.{...}
> log("4")
> info("5")
> ```

that is not cool

**Comment by fuqiuluo** [comment]
> > * Change the package from '@get' to 'use'
> > 
> > ```
> > use console
> > console.log("1")
> > 
> > use console as con
> > con.log("2")
> > 
> > use console.{log, info}
> > log("3")
> > 
> > use console.{...}
> > log("4")
> > info("5")
> > ```
> 
> that is not cool

Please list the reasons.

**Comment by ScSofts** [comment]
好好好
